language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# command to install program dependencies (PyCA cryptography) and compatibility test dependencies (AES Crypt)
install:
  - pip install cryptography
  - wget https://www.aescrypt.com/download/v3/linux/aescrypt-3.14.tgz
  - tar -xzf aescrypt-3.14.tgz
  - pushd aescrypt-3.14/src && make && sudo make install && popd

# command to run tests
script: python -m unittest discover

